name: pdf_maker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.2.0 <4.0.0"

dependencies:
    auto_route: ^7.8.4
    dartz: ^0.10.1
    flex_color_scheme: ^7.3.1
    flutter:
        sdk: flutter
    flutter_image_compress: ^2.1.0
    flutter_pdfview: ^1.3.2
    flutter_riverpod: ^2.4.9
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    image_picker: ^1.0.5
    intl: ^0.19.0
    json_annotation: ^4.8.1
    path: ^1.9.0
    path_provider: ^2.1.1
    pdf: ^3.10.7
    riverpod: ^2.4.9
    share_plus: ^7.2.1
    uuid: ^4.3.1
    vibration: ^1.8.4

dev_dependencies:
    auto_route_generator: ^7.3.2
    build_runner: ^2.4.7
    flutter_launcher_icons: ^0.13.1
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    freezed: ^2.4.6
    json_serializable: ^6.7.1
    lint: ^2.2.0
    logger: ^2.0.2+1

dependency_overrides:
    path: 1.8.3

flutter:
    uses-material-design: true
    fonts:
      - family: Rubik
        fonts:
            - asset: assets/fonts/Rubik-Regular.ttf
            - asset: assets/fonts/Rubik-Bold.ttf
            - asset: assets/fonts/Rubik-SemiBold.ttf
      


